/*
  The wheeze classifier, running directly on the ESP32.

  Four convolutions, a time average and one linear layer, written out rather
  than run through an interpreter. `wheeze_model.h` holds the weights and is
  generated by export_weights.py — regenerate it after every training run, or
  the device keeps running whichever model was exported last while the metrics
  being quoted describe a different one.

  Two things here are worth reading before changing anything.

  *Each convolution is fused with the pooling that follows it.* Computed
  separately, the first layer's output is 16 x 40 x 251 floats — 642 KB, on a
  chip with 512 KB of internal RAM, so the straightforward version does not run
  at all. Writing directly into the pooled output, and keeping only the few
  convolution rows a pooling window needs, drops that layer's cost to 156 KB.

  *The activation buffers prefer PSRAM.* Even fused, the working set is about
  230 KB, which is most of the internal RAM on a bare S3 and leaves too little
  for the I2S buffers and the display. On a DevKitC-1 with PSRAM fitted these
  land there and internal RAM stays free; without PSRAM the allocation falls
  back to internal and begin() reports whether it succeeded rather than
  crashing later inside predict().
*/

#pragma once

#include <esp_heap_caps.h>
#include <math.h>

#include "wheeze_model.h"

// Layer geometry. These follow from the architecture in train_wheeze.py and
// the patch shape in wheeze.h; changing either means changing these.
#define L0_M  40
#define L0_T  251
#define L1_C  16
#define L1_M  20
#define L1_T  125
#define L2_C  32
#define L2_M  10
#define L2_T  62
#define L3_C  64
#define L3_M  10
#define L3_T  31
#define L4_C  64
#define L4_M  10
#define L4_T  15

class WheezeClassifier {
 public:
  bool begin() {
    // Sized for the two largest activations. Layer 3 reuses layer 1's buffer
    // and layer 4 reuses layer 2's, so two allocations cover all four.
    bufA_ = alloc(L1_C * L1_M * L1_T);   // 40000 floats, 156 KB
    bufB_ = alloc(L2_C * L2_M * L2_T);   // 19840 floats,  78 KB
    ready_ = (bufA_ && bufB_);
    return ready_;
  }

  bool ready() const { return ready_; }

  /*
    Score one standardised log-mel patch, laid out [mel][frame].
    Returns wheeze confidence in 0..1.
  */
  float predict(const float *patch) {
    if (!ready_) return 0.0f;

    convPool(patch,  1, L0_M, L0_T, bufA_, L1_C, 2, 2, WZ_W1, WZ_B1);
    convPool(bufA_, L1_C, L1_M, L1_T, bufB_, L2_C, 2, 2, WZ_W2, WZ_B2);
    convPool(bufB_, L2_C, L2_M, L2_T, bufA_, L3_C, 1, 2, WZ_W3, WZ_B3);
    convPool(bufA_, L3_C, L3_M, L3_T, bufB_, L4_C, 1, 2, WZ_W4, WZ_B4);

    // Collapse time, keep the frequency bands — the head expects [channel][mel]
    // flattened, which is the order PyTorch's flatten(1) produces.
    static float pooled[L4_C * L4_M];
    for (int c = 0; c < L4_C; c++) {
      for (int m = 0; m < L4_M; m++) {
        float acc = 0.0f;
        const float *row = bufB_ + (c * L4_M + m) * L4_T;
        for (int t = 0; t < L4_T; t++) acc += row[t];
        pooled[c * L4_M + m] = acc / L4_T;
      }
    }

    float logit = WZ_HEAD_B[0];
    for (int i = 0; i < L4_C * L4_M; i++) logit += WZ_HEAD_W[i] * pooled[i];
    return 1.0f / (1.0f + expf(-logit));
  }

 private:
  float *bufA_ = nullptr;
  float *bufB_ = nullptr;
  bool ready_ = false;

  static float *alloc(int n) {
    // PSRAM first; internal RAM only if this board has none fitted.
    float *p = (float *)heap_caps_malloc(n * sizeof(float), MALLOC_CAP_SPIRAM);
    if (!p) p = (float *)heap_caps_malloc(n * sizeof(float), MALLOC_CAP_8BIT);
    return p;
  }

  /*
    3x3 convolution with padding 1, ReLU, then max pooling — all in one pass.

    The output element at (co, mo, to) is the maximum over its pooling window of
    the convolution's ReLU output. Computing it this way means the convolution
    result for a position is used the moment it is produced and never stored, so
    the full pre-pool activation never exists in memory.

    Weights are [out][in][3][3], matching PyTorch's layout, with batch-norm
    already folded in by the export script.
  */
  void convPool(const float *in, int cin, int hin, int win,
                float *out, int cout, int poolH, int poolW,
                const float *w, const float *b) {
    const int hout = hin / poolH;
    const int wout = win / poolW;

    for (int co = 0; co < cout; co++) {
      const float bias = b[co];
      for (int mo = 0; mo < hout; mo++) {
        for (int to = 0; to < wout; to++) {
          float best = 0.0f;   // ReLU floor: nothing below zero survives anyway

          for (int py = 0; py < poolH; py++) {
            const int m = mo * poolH + py;
            for (int px = 0; px < poolW; px++) {
              const int t = to * poolW + px;

              float acc = bias;
              for (int ci = 0; ci < cin; ci++) {
                const float *plane = in + ci * hin * win;
                const float *k = w + ((co * cin + ci) * 9);
                for (int ky = -1; ky <= 1; ky++) {
                  const int y = m + ky;
                  if (y < 0 || y >= hin) continue;
                  for (int kx = -1; kx <= 1; kx++) {
                    const int x = t + kx;
                    if (x < 0 || x >= win) continue;
                    acc += plane[y * win + x] * k[(ky + 1) * 3 + (kx + 1)];
                  }
                }
              }
              if (acc > best) best = acc;
            }
          }
          out[(co * hout + mo) * wout + to] = best;
        }
      }
    }
  }
};
